### ISSUE TITLE
Перероблення кнопок з компонентом Icon

### ISSUE THREAD

**Issue by nazor1k** [Natus-Vincere-Programming/MindGlow-application#19]

**Comment by Xemii16** [comment]
1. Треба зробити можливість додати справа або зліва іконку для кнопок ![image](https://github.com/Natus-Vincere-Programming/MindGlow-application/assets/113195769/6e18c386-1999-484d-8a49-b7dbff134b2d)
2. Пофіксити помилку ` Can't bind to 'ngIf' since it isn't a known property of 'app-icon' (used in the '_ButtonComponent' component template). If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is included in the '@Component.imports' of this component.
` яка виникає під час користування
3. Прописати стилі в button.component.css ![image](https://github.com/Natus-Vincere-Programming/MindGlow-application/assets/113195769/c9fa24c4-1ca6-42d6-bda4-f002a8f25818)
4. Замінити enum на КАПC: Big - BIG ![image](https://github.com/Natus-Vincere-Programming/MindGlow-application/assets/113195769/6f29b4bf-0872-42e4-a17e-e2e47ff87548)
5. Зробити кнопки responsive
6. Зробити відступи такі самі як у Figma
7. Зробити шрифт і кольора як у Figma

**Comment by Xemii16** [comment]
- [ ] Назвати css класи згідно [нормам](https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/)
